# Name of the workflow
name: Build APK

 # Controls what will trigger the workflow.
 # Change it to your needs.
on:
 # A new push to the "main" branch. 
  push:
   branches: [ "master", "dev" ]
 # A new pull request to the "main" branch.
  pull_request:
   branches: [ "master", "dev" ]

 
# A single workflow can have multiple jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk